Potions:
  - lingering_potion
  - potion{Potion:water}
  - potion{Potion:empty}
  - potion{Potion:awkward}
  - potion{Potion:thick}
  - potion{Potion:mundane}
  - potion{Potion:regeneration}
  - potion{Potion:swiftness}
  - potion{Potion:fire_resistance}
  - potion{Potion:poison}
  - potion{Potion:healing}
  - potion{Potion:night_vision}
  - potion{Potion:weakness}
  - potion{Potion:strength}
  - potion{Potion:slowness}
  - potion{Potion:harming}
  - potion{Potion:water_breathing}
  - potion{Potion:invisibility}
  - potion{Potion:strong_regeneration}
  - potion{Potion:strong_swiftness}
  - potion{Potion:strong_poison}
  - potion{Potion:strong_healing}
  - potion{Potion:strong_strength}
  - potion{Potion:strong_leaping}
  - potion{Potion:strong_harming}
  - potion{Potion:long_regeneration}
  - potion{Potion:long_swiftness}
  - potion{Potion:long_fire_resistance}
  - potion{Potion:long_poison}
  - potion{Potion:long_night_vision}
  - potion{Potion:long_weakness}
  - potion{Potion:long_strength}
  - potion{Potion:long_slowness}
  - potion{Potion:leaping}
  - potion{Potion:long_water_breathing}
  - potion{Potion:long_invisibility}
  - potion{Potion:turtle_master}
  - potion{Potion:long_turtle_master}
  - potion{Potion:strong_turtle_master}
  - potion{Potion:slow_falling}
  - potion{Potion:long_slow_falling}
  - splash_potion{Potion:regeneration}
  - splash_potion{Potion:swiftness}
  - splash_potion{Potion:fire_resistance}
  - splash_potion{Potion:poison}
  - splash_potion{Potion:healing}
  - splash_potion{Potion:night_vision}
  - splash_potion{Potion:weakness}
  - splash_potion{Potion:strength}
  - splash_potion{Potion:slowness}
  - splash_potion{Potion:harming}
  - splash_potion{Potion:water_breathing}
  - splash_potion{Potion:invisibility}
  - splash_potion{Potion:strong_regeneration}
  - splash_potion{Potion:strong_swiftness}
  - splash_potion{Potion:strong_poison}
  - splash_potion{Potion:strong_healing}
  - splash_potion{Potion:strong_leaping}
  - splash_potion{Potion:strong_harming}
  - splash_potion{Potion:long_regeneration}
  - splash_potion{Potion:long_swiftness}
  - splash_potion{Potion:long_fire_resistance}
  - splash_potion{Potion:long_poison}
  - splash_potion{Potion:long_night_vision}
  - splash_potion{Potion:long_weakness}
  - splash_potion{Potion:long_strength}
  - splash_potion{Potion:long_slowness}
  - splash_potion{Potion:leaping}
  - splash_potion{Potion:long_water_breathing}
  - splash_potion{Potion:long_invisibility}
  - splash_potion{Potion:strong_strength}
  - splash_potion{Potion:turtle_master}
  - splash_potion{Potion:long_turtle_master}
  - splash_potion{Potion:strong_turtle_master}
  - splash_potion{Potion:slow_falling}
  - splash_potion{Potion:long_slow_falling}

Small_List:
  - cactus_green
Tier1_Items:
  - glass_bottle
  - sweet_berries
  - campfire
  - honeycomb
  - bee_nest
  - beehive
  - honey_bottle
  - honey_block
  - honeycomb_block
  - sweet_berry_bush
  - target
  - composter
  - oak_sign
  - spruce_sign
  - birch_sign
  - jungle_sign
  - acacia_sign
  - dark_oak_sign
  - bamboo
  - red_dye
  - green_dye
  - yellow_dye
  - blue_dye
  - brown_dye
  - black_dye
  - white_dye
  - crossbow
  - suspicious_stew
  - loom
  - flower_banner_pattern
  - creeper_banner_pattern
  - skull_banner_pattern
  - mojang_banner_pattern
  - globe_banner_pattern
  - barrel
  - smoker
  - blast_furnace
  - cartography_table
  - fletching_table
  - grindstone
  - lectern
  - smithing_table
  - stonecutter
  - bell
  - lantern
  - smooth_stone_slab
  - cut_sandstone_slab
  - cut_red_sandstone_slab
  - brick_wall
  - prismarine_wall
  - red_sandstone_wall
  - mossy_stone_brick_wall
  - granite_wall
  - stone_brick_wall
  - nether_brick_wall
  - andesite_wall
  - red_nether_brick_wall
  - sandstone_wall
  - end_stone_brick_wall
  - diorite_wall
  - polished_granite_stairs
  - smooth_red_sandstone_stairs
  - mossy_stone_brick_stairs
  - polished_diorite_stairs
  - mossy_cobblestone_stairs
  - end_stone_brick_stairs
  - stone_stairs
  - smooth_sandstone_stairs
  - smooth_quartz_stairs
  - granite_stairs
  - andesite_stairs
  - red_nether_brick_stairs
  - polished_andesite_stairs
  - diorite_stairs
  - polished_granite_slab
  - smooth_red_sandstone_slab
  - mossy_stone_brick_slab
  - polished_diorite_slab
  - mossy_cobblestone_slab
  - end_stone_brick_slab
  - smooth_sandstone_slab
  - smooth_quartz_slab
  - granite_slab
  - andesite_slab
  - red_nether_brick_slab
  - polished_andesite_slab
  - diorite_slab
  - scaffolding
  - flower_pot
  - cocoa
  - tripwire
  - tripwire_hook
  - potted_oak_sapling
  - potted_spruce_sapling
  - potted_birch_sapling
  - potted_jungle_sapling
  - potted_acacia_sapling
  - potted_dark_oak_sapling
  - potted_fern
  - potted_dandelion
  - shield
  - spruce_boat
  - birch_boat
  - jungle_boat
  - acacia_boat
  - dark_oak_boat
  - mutton
  - cooked_mutton
  - white_banner
  - orange_banner
  - magenta_banner
  - light_blue_banner
  - yellow_banner
  - lime_banner
  - pink_banner
  - gray_banner
  - light_gray_banner
  - cyan_banner
  - purple_banner
  - blue_banner
  - brown_banner
  - green_banner
  - red_banner
  - black_banner
  - beetroot
  - beetroot_seeds
  - beetroot_soup
  - carrot_on_a_stick
  - pumpkin_pie
  - flower_pot
  - carrot
  - potato
  - baked_potato
  - poisonous_potato
  - map
  - item_frame
  - gold_nugget
  - spider_eye
  - fermented_spider_eye
  - sugar_cane
  - reeds
  - kelp
  - dried_kelp
  - dried_kelp_block
  - paper
  - book
  - egg
  - fishing_rod
  - cod
  - fish
  - salmon
  - tropical_fish
  - pufferfish
  - cooked_cod
  - cooked_salmon
  - ink_sac
  - cocoa_beans
  - lapis_lazuli
  - purple_dye
  - cyan_dye
  - light_gray_dye
  - gray_dye
  - pink_dye
  - lime_dye
  - dandelion_yellow
  - light_blue_dye
  - magenta_dye
  - orange_dye
  - bone_meal
  - bone
  - sugar
  - cake
  - white_bed
  - orange_bed
  - magenta_bed
  - light_blue_bed
  - yellow_bed
  - lime_bed
  - pink_bed
  - gray_bed
  - light_gray_bed
  - cyan_bed
  - purple_bed
  - blue_bed
  - brown_bed
  - green_bed
  - red_bed
  - black_bed
  - sign
  - bucket
  - water_bucket
  - lava_bucket
  - apple
  - stick
  - bowl
  - mushroom_stew
  - turtle_egg
  - string
  - feather
  - wooden_hoe
  - stone_hoe
  - iron_hoe
  - golden_hoe
  - dead_tube_coral_block
  - dead_brain_coral_block
  - dead_bubble_coral_block
  - dead_fire_coral_block
  - dead_horn_coral_block
  - tube_coral_block
  - brain_coral_block
  - bubble_coral_block
  - fire_coral_block
  - horn_coral_block
  - tube_coral
  - brain_coral
  - bubble_coral
  - fire_coral
  - horn_coral
  - dead_brain_coral
  - dead_bubble_coral
  - dead_fire_coral
  - dead_horn_coral
  - dead_tube_coral
  - tube_coral_fan
  - lilac
  - rose_bush
  - peony
  - tall_grass
  - large_fern
  - sunflower
  - bone_block
  - porkchop
  - cooked_porkchop
  - cookie
  - chicken
  - cooked_chicken
  - beef
  - cooked_beef
  - charcoal
  - wheat_seeds
  - bread
  - leather_helmet
  - leather_chestplate
  - leather_leggings
  - leather_boots
  - stone
  - granite
  - polished_granite
  - diorite
  - polished_diorite
  - andesite
  - polished_andesite
  - grass_block
  - grass
  - dirt
  - coarse_dirt
  - podzol
  - cobblestone
  - oak_planks
  - spruce_planks
  - birch_planks
  - jungle_planks
  - acacia_planks
  - dark_oak_planks
  - oak_sapling
  - spruce_sapling
  - birch_sapling
  - jungle_sapling
  - acacia_sapling
  - dark_oak_sapling
  - sand
  - red_sand
  - gravel
  - oak_log
  - spruce_log
  - birch_log
  - jungle_log
  - acacia_log
  - dark_oak_log
  - stripped_oak_log
  - stripped_spruce_log
  - stripped_birch_log
  - stripped_jungle_log
  - stripped_acacia_log
  - stripped_dark_oak_log
  - stripped_oak_wood
  - stripped_spruce_wood
  - stripped_birch_wood
  - stripped_jungle_wood
  - stripped_acacia_wood
  - stripped_dark_oak_wood
  - oak_wood
  - spruce_wood
  - birch_wood
  - jungle_wood
  - acacia_wood
  - dark_oak_wood
  - oak_leaves
  - spruce_leaves
  - birch_leaves
  - jungle_leaves
  - acacia_leaves
  - dark_oak_leaves
  - sponge
  - wet_sponge
  - glass
  - lapis_ore
  - lapis_block
  - dispenser
  - red_sandstone
  - chiseled_red_sandstone
  - cut_red_sandstone
  - red_sandstone_stairs
  - sandstone
  - chiseled_sandstone
  - cut_sandstone
  - note_block
  - minecart
  - saddle
  - powered_rail
  - detector_rail
  - sticky_piston
  - cobweb
  - fern
  - dead_bush
  - seagrass
  - sea_pickle
  - piston
  - white_wool
  - orange_wool
  - magenta_wool
  - light_blue_wool
  - yellow_wool
  - lime_wool
  - pink_wool
  - gray_wool
  - light_gray_wool
  - cyan_wool
  - purple_wool
  - blue_wool
  - brown_wool
  - green_wool
  - red_wool
  - black_wool
  - dandelion
  - poppy
  - blue_orchid
  - allium
  - azure_bluet
  - red_tulip
  - orange_tulip
  - white_tulip
  - pink_tulip
  - oxeye_daisy
  - brown_mushroom
  - red_mushroom
  - gold_block
  - iron_block
  - oak_slab
  - spruce_slab
  - birch_slab
  - jungle_slab
  - acacia_slab
  - dark_oak_slab
  - stone_slab
  - sandstone_slab
  - petrified_oak_slab
  - cobblestone_slab
  - brick_slab
  - stone_brick_slab
  - nether_brick_slab
  - quartz_slab
  - red_sandstone_slab
  - purpur_slab
  - prismarine_shard
  - prismarine_crystals
  - rabbit
  - cooked_rabbit
  - rabbit_stew
  - rabbit_foot
  - rabbit_hide
  - armor_stand
  - iron_horse_armor
  - golden_horse_armor
  - diamond_horse_armor
  - lead
  - name_tag
  - mutton
  - prismarine_slab
  - prismarine_brick_slab
  - dark_prismarine_slab
  - smooth_quartz
  - smooth_red_sandstone
  - smooth_sandstone
  - smooth_stone
  - bricks
  - bookshelf
  - mossy_cobblestone
  - obsidian
  - torch
  - oak_stairs
  - chest
  - crafting_table
  - farmland
  - wheat
  - painting
  - furnace
  - ladder
  - rail
  - cobblestone_stairs
  - stone_stairs
  - lever
  - stone_pressure_plate
  - oak_pressure_plate
  - wooden_pressure_plate
  - spruce_pressure_plate
  - birch_pressure_plate
  - jungle_pressure_plate
  - acacia_pressure_plate
  - dark_oak_pressure_plate
  - wooden_sword
  - wooden_shovel
  - wooden_pickaxe
  - wooden_axe
  - stone_sword
  - stone_shovel
  - stone_pickaxe
  - stone_axe
  - redstone_ore
  - redstone_torch
  - stone_button
  - snow
  - ice
  - snow_block
  - cactus
  - clay
  - jukebox
  - oak_fence
  - spruce_fence
  - birch_fence
  - jungle_fence
  - acacia_fence
  - dark_oak_fence
  - pumpkin
  - pumpkin_seeds
  - carved_pumpkin
  - netherrack
  - soul_sand
  - glowstone
  - jack_o_lantern
  - oak_trapdoor
  - spruce_trapdoor
  - birch_trapdoor
  - jungle_trapdoor
  - acacia_trapdoor
  - dark_oak_trapdoor
  - oak_door
  - spruce_door
  - birch_door
  - jungle_door
  - acacia_door
  - dark_oak_door
  - infested_stone
  - infested_cobblestone
  - infested_stone_bricks
  - infested_mossy_stone_bricks
  - infested_cracked_stone_bricks
  - infested_chiseled_stone_bricks
  - stone_bricks
  - mossy_stone_bricks
  - cracked_stone_bricks
  - chiseled_stone_bricks
  - brown_mushroom_block
  - red_mushroom_block
  - mushroom_stem
  - iron_bars
  - glass_pane
  - melon
  - melon_seeds
  - rotten_flesh
  - ender_pearl
  - vine
  - oak_fence_gate
  - spruce_fence_gate
  - birch_fence_gate
  - jungle_fence_gate
  - acacia_fence_gate
  - dark_oak_fence_gate
  - brick_stairs
  - stone_brick_stairs
  - mycelium
  - lily_pad
  - nether_bricks
  - nether_brick_fence
  - nether_brick_stairs
  - enchanting_table
  - end_portal_frame
  - end_stone
  - end_stone_bricks
  - dragon_egg
  - redstone_lamp
  - sandstone_stairs
  - ender_chest
  - tripwire
  - spruce_stairs
  - birch_stairs
  - jungle_stairs
  - acacia_stairs
  - dark_oak_stairs
  - command_block
  - cobblestone_wall
  - mossy_cobblestone_wall
  - oak_button
  - spruce_button
  - birch_button
  - jungle_button
  - acacia_button
  - dark_oak_button
  - anvil
  - chipped_anvil
  - damaged_anvil
  - trapped_chest
  - light_weighted_pressure_plate
  - heavy_weighted_pressure_plate
  - daylight_detector
  - redstone_block
  - hopper
  - chiseled_quartz_block
  - activator_rail
  - dropper
  - white_terracotta
  - orange_terracotta
  - magenta_terracotta
  - light_blue_terracotta
  - yellow_terracotta
  - lime_terracotta
  - pink_terracotta
  - gray_terracotta
  - light_gray_terracotta
  - cyan_terracotta
  - purple_terracotta
  - blue_terracotta
  - brown_terracotta
  - green_terracotta
  - red_terracotta
  - black_terracotta
  - cornflower
  - lily_of_the_valley
  - wither_rose
  - iron_trapdoor
  - hay_block
  - white_carpet
  - orange_carpet
  - magenta_carpet
  - light_blue_carpet
  - yellow_carpet
  - lime_carpet
  - pink_carpet
  - gray_carpet
  - light_gray_carpet
  - cyan_carpet
  - purple_carpet
  - blue_carpet
  - brown_carpet
  - green_carpet
  - red_carpet
  - black_carpet
  - terracotta
  - snowball
  - oak_boat
  - leather
  - milk_bucket
  - pufferfish_bucket
  - salmon_bucket
  - cod_bucket
  - tropical_fish_bucket
  - brick
  - clay_ball
  - shears
  - chest_minecart
  - furnace_minecart
  - compass
  - clock
  - turtle_helmet
  - scute
  - bow
  - arrow
  - flint_and_steel
  - iron_door
  - iron_block
  - iron_bars
  - iron_trapdoor
  - iron_nugget
  - iron_hoe
  - gold_ore
  - iron_ore
  - coal_ore
  - coal_block
  - packed_ice
  - blue_ice
  - bedrock
  - iron_sword
  - iron_pickaxe
  - iron_shovel
  - iron_axe
  - golden_sword
  - golden_pickaxe
  - golden_shovel
  - golden_axe
  - chainmail_helmet
  - chailmail_leggings
  - chainmail_chestplate
  - chainmail_boots
  - iron_helmet
  - iron_chestplate
  - iron_leggings
  - iron_boots
  - golden_helmet
  - golden_boots
  - golden_chestplate
  - golden_leggings
  - flint
  - tnt
  - diamond_ore
  - redstone
  - observer
  - redstone_ore
  - redstone_lamp
  - redstone_torch
  - repeater
  - comparator
  - redstone_block
  - lever
  - slime_ball
  - slime_block
  - white_stained_glass
  - orange_stained_glass
  - magenta_stained_glass
  - light_blue_stained_glass
  - yellow_stained_glass
  - lime_stained_glass
  - pink_stained_glass
  - gray_stained_glass
  - light_gray_stained_glass
  - cyan_stained_glass
  - purple_stained_glass
  - blue_stained_glass
  - brown_stained_glass
  - green_stained_glass
  - red_stained_glass
  - black_stained_glass
  - white_stained_glass_pane
  - orange_stained_glass_pane
  - magenta_stained_glass_pane
  - light_blue_stained_glass_pane
  - yellow_stained_glass_pane
  - lime_stained_glass_pane
  - pink_stained_glass_pane
  - gray_stained_glass_pane
  - light_gray_stained_glass_pane
  - cyan_stained_glass_pane
  - purple_stained_glass_pane
  - blue_stained_glass_pane
  - brown_stained_glass_pane
  - green_stained_glass_pane
  - red_stained_glass_pane
  - black_stained_glass_pane
  - prismarine
  - prismarine_bricks
  - dark_prismarine
  - prismarine_stairs
  - prismarine_brick_stairs
  - dark_prismarine_stairs
  - sea_lantern
  - white_glazed_terracotta
  - orange_glazed_terracotta
  - magenta_glazed_terracotta
  - light_blue_glazed_terracotta
  - yellow_glazed_terracotta
  - lime_glazed_terracotta
  - pink_glazed_terracotta
  - gray_glazed_terracotta
  - light_gray_glazed_terracotta
  - cyan_glazed_terracotta
  - purple_glazed_terracotta
  - blue_glazed_terracotta
  - brown_glazed_terracotta
  - green_glazed_terracotta
  - red_glazed_terracotta
  - black_glazed_terracotta
  - white_concrete
  - orange_concrete
  - magenta_concrete
  - light_blue_concrete
  - yellow_concrete
  - lime_concrete
  - pink_concrete
  - gray_concrete
  - light_gray_concrete
  - cyan_concrete
  - purple_concrete
  - blue_concrete
  - brown_concrete
  - green_concrete
  - red_concrete
  - black_concrete
  - white_concrete_powder
  - orange_concrete_powder
  - magenta_concrete_powder
  - light_blue_concrete_powder
  - yellow_concrete_powder
  - lime_concrete_powder
  - pink_concrete_powder
  - gray_concrete_powder
  - light_gray_concrete_powder
  - cyan_concrete_powder
  - purple_concrete_powder
  - blue_concrete_powder
  - brown_concrete_powder
  - green_concrete_powder
  - red_concrete_powder
  - black_concrete_powder
Tier2_Items:
  - emerald_block
  - emerald_ore
  - phantom_membrane
  - nautilus_shell
  - heart_of_the_sea
  - iron_nugget
  - tnt_minecart
  - hopper_minecart
  - spectral_arrow
  - firework_rocket
  - golden_carrot
  - fire_charge
  - experience_bottle
  - writable_book
  - emerald
  - wither_skeleton_skull
  - skeleton_skull
  - zombie_skull
  - creeper_skull
  - glistering_melon_slice
  - cauldron
  - brewing_stand
  - golden_apple
  - quartz
  - quartz_block
  - quartz_pillar
  - quartz_stairs
  - nether_quartz_ore
  - obsidian
  - diamond
  - diamond_block
  - diamond_sword
  - diamond_pickaxe
  - diamond_axe
  - diamond_shovel
  - diamond_chestplate
  - diamond_helmet
  - diamond_boots
  - diamond_leggings
  - magma_block
  - nether_wart_block
  - red_nether_bricks
  - nether_wart
  - conduit
  - beacon
  - diamond_hoe
  - glowstone_dust
  - ender_eye
  - blaze_rod
  - blaze_powder
  - ghast_tear
  - magma_cream
  - crimson_nylium
  - warped_nylium
  - crimson_planks
  - warped_planks
  - nether_gold_ore
  - crimson_stem
  - warped_stem
  - stripped_crimson_stem
  - stripped_warped_stem
  - stripped_crimson_hyphae
  - stripped_warped_hyphae
  - crimson_hyphae
  - warped_hyphae
  - crimson_fungus
  - warped_fungus
  - crimson_roots
  - warped_roots
  - nether_sprouts
  - weeping_vines
  - twisting_vines
  - crimson_slab
  - warped_slab
  - crimson_pressure_plate
  - warped_pressure_plate
  - polished_blackstone_pressure_plate
  - crimson_fence
  - warped_fence
  - soul_soil
  - basalt
  - polished_basalt
  - soul_torch
  - crimson_trapdoor
  - warped_trapdoor
  - chain
  - crimson_sign
  - warped_sign
  - crimson_fence_gate
  - warped_fence_gate
  - cracked_nether_bricks
  - chiseled_nether_bricks
  - crimson_stairs
  - warped_stairs
  - blackstone_wall
  - polished_blackstone_wall
  - polished_blackstone_brick_wall
  - crimson_button
  - warped_button
  - polished_blackstone_button
  - quartz_bricks
  - warped_wart_block
  - crimson_door
  - warped_door
  - warped_fungus_on_a_stick
  - soul_lantern
  - soul_campfire
  - shroomlight
  - crying_obsidian
  - blackstone
  - blackstone_slab
  - blackstone_stairs
  - gilded_blackstone
  - polished_blackstone
  - polished_blackstone_slab
  - polished_blackstone_stairs
  - chiseled_polished_blackstone
  - polished_blackstone_bricks
  - polished_blackstone_brick_slab
  - polished_blackstone_brick_stairs
  - cracked_polished_blackstone_bricks
  - respawn_anchor
  - soul_fire
  - soul_wall_torch
  - weeping_vines_plant
  - twisting_vines_plant
  - crimson_wall_sign
  - warped_wall_sign
  - potted_crimson_fungus
  - potted_warped_fungus
  - potted_crimson_roots
  - potted_warped_roots
Tier3_Items:
  - enchanted_golden_apple
  - beacon
  - music_disc_pigstep
  - piglin_banner_pattern
  - lodestone
  - netherite_block
  - ancient_debris
  - netherite_ingot
  - netherite_scrap
  - netherite_sword
  - netherite_shovel
  - netherite_pickaxe
  - netherite_axe
  - netherite_hoe
  - netherite_helmet
  - netherite_chestplate
  - netherite_leggings
  - netherite_boots
  - end_gateway
  - trident
  - music_disc_13
  - music_disc_cat
  - music_disc_blocks
  - music_disc_chirp
  - music_disc_far
  - music_disc_mall
  - music_disc_mellohi
  - music_disc_stal
  - music_disc_strad
  - music_disc_ward
  - music_disc_11
  - music_disc_wait
  - totem_of_undying
  - shulker_shell
  - dragon_breath
  - elytra
  - dragon_head
  - nether_star
  - end_rod
  - chorus_plant
  - chorus_flower
  - purpur_block
  - purpur_pillar
  - purpur_stairs
  - spawner
  - shulker_box
  - white_shulker_box
  - orange_shulker_box
  - magenta_shulker_box
  - light_blue_shulker_box
  - yellow_shulker_box
  - lime_shulker_box
  - pink_shulker_box
  - gray_shulker_box
  - light_gray_shulker_box
  - cyan_shulker_box
  - purple_shulker_box
  - blue_shulker_box
  - brown_shulker_box
  - green_shulker_box
  - red_shulker_box
  - black_shulker_box
  - end_crystal
  - chorus_fruit
  - popped_chorus_fruit



